image:
  repository: localhost:30500/sentinel-data-plane
  tag: "latest"
  pullPolicy: Always

serviceAccount:
  create: true
  name: "sentinel-data-plane"

containerPort: 15006

initContainer:
  name: sentinel-init
  image:
    repository: localhost:30500/sentinel-init
    tag: "latest"
    pullPolicy: IfNotPresent
  inboundPort: 15006
  outboundPort: 15001

controlPlane:
  serviceName: sentinel-control-plane
  namespace: sentinel-control-plane
  port: 8081
  grpcPort: 9090
caSecretName: sentinel-root-ca

spiffe:
  trustDomain: cluster.local

containers:
  name: sentinel-data-plane

service:
  type: NodePort
  port: 15006
  nodePort: 30443

fullnameOverride: "sentinel-data-plane"
