apiVersion: v1
kind: Secret
metadata:
  name: users-service-secret
  namespace: users-service
type: Opaque
stringData:
  PORT: "3005"
  HOST: "0.0.0.0"
  LOOP_INTERVAL_MS: "15000"
  ECHO_SERVICE_URL: "http://echo-service.echo-service.svc.cluster.local/api/health"
