apiVersion: v1
kind: Secret
metadata:
  name: users-service-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgresql-primary-hl.database:5432/postgres?sslmode=disable"
  PORT: "3005"
  HOST: "0.0.0.0"
