architecture: replication

primary:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistance:
    enabled: true
    size: 8Gi

readReplicas:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

pgbouncer:
  enabled: true

auth:
  existingSecret: postgres-credentials

image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 17.5.0-debian-12-r12
  pullPolicy: IfNotPresent
