architecture: replication

primary:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  persistence:
    enabled: true
    size: 8Gi

readReplicas:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

pgbouncer:
  enabled: true
  pgbouncerConfiguration: |
    [database]
    postgres = host=postgresql-primary user=postgres password=${POSTGRES_PASSWORD} port=5432 dbname=postgres
    [pgbouncer]
    pool_mode = transaction
    max_client_conn = 100
    default_pool_size = 20

auth:
  existingSecret: postgres-credentials

image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: 17.5.0-debian-12-r12
  pullPolicy: IfNotPresent
