services:
  vault:
    restart: unless-stopped
    privileged: true
    image: hashicorp/vault:1.15
    container_name: sentinel-vault
    ports:
      - "8200:8200"
      - "443:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_API_ADDR: http://127.0.0.1:8200
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - /var/services/vault/audit:/vault/audit
      - /var/services/vault/config:/vault/config
      - /var/services/vault/data:/vault/data
      - /var/services/vault/file:/vault/file
      - /var/services/vault/logs:/vault/logs
      - /var/services/vault/userconfig:/vault/userconfig
      - /var/services/vault/plugins:/vault/plugins
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
  opa:
    image: openpolicyagent/opa:0.36.0-rootless
    container_name: sentinel-opa
    ports:
      - "8181:8181"
    command: "run --server --log-level debug"
  loki:
    image: grafana/loki:2.8.2
    container_name: sentinel-loki
    volumes:
      - sentinel-loki-data:/loki
    ports:
      - "3100:3100"
  promtail:
    image: grafana/promtail:2.8.2
    container_name: sentinel-promtail
    volumes:
      - /var/services/promtail/config.yml:/etc/promtail/config.yaml
      - ./logs/proxy:/var/log/host-apps
    command: "-config.expand-env=true -config.file=/etc/promtail/config.yaml"
    depends_on:
      - loki
  grafana:
    image: grafana/grafana:9.5.2
    container_name: sentinel-grafana
    volumes:
      - sentinel-grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
volumes:
  sentinel-grafana-data:
  sentinel-loki-data:
