apiVersion: v2
name: sentinel-control-plane
description: A Zero Trust Control Plane for automated mTLS and identity verification.

version: 0.1.0
appVersion: "1.2.0"

home: https://github.com/SamSyntel/sentinel-zt
maintainers:
  - name: SamSyntax
    email: sam@samsyntax.dev

keywords:
  - zero-trust
  - mTLS
  - security
  - identity
  - control-plane
