image:
  repository: localhost:30500/sentinel-control-plane
  tag: "latest"
  pullPolicy: IfNotPresent

rbac:
  create: true

serviceAccount:
  create: true
  name: "sentinel-control-plane"

vault:
  uri: "http://vault-internal.default.svc.cluster.local:8200"

containers:
  name: sentinel-control-plane
  port: 8081
  grpcPort: 9090

labels:
  app: sentinel-control-plane

fullnameOverride: "sentinel-control-plane"

spiffe:
  trustDomain: "cluster.local"

service:
  type: ClusterIP
  port: 8081
