apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sentinel-sidecar-injector
webhooks:
  - name: injector.sentinel-zt.io
    clientConfig:
      service:
        name: sentinel-control-plane
        namespace: sentinel-control-plane
        path: "/webhook/mutate"
        port: 8081
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    namespaceSelector:
      matchLabels:
        sentinel-zt.io/injection: enabled
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - sentinel-control-plane
            - sentinel-data-plane
            - kube-system
            - argocd
