// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: certificate_issue_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateRequest) Reset() {
	*x = CertificateRequest{}
	mi := &file_certificate_issue_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateRequest) ProtoMessage() {}

func (x *CertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_issue_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateRequest.ProtoReflect.Descriptor instead.
func (*CertificateRequest) Descriptor() ([]byte, []int) {
	return file_certificate_issue_service_proto_rawDescGZIP(), []int{0}
}

func (x *CertificateRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type CertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificate   string                 `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	IssuingCa     string                 `protobuf:"bytes,3,opt,name=issuing_ca,json=issuingCa,proto3" json:"issuing_ca,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	PodUid        string                 `protobuf:"bytes,5,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertificateResponse) Reset() {
	*x = CertificateResponse{}
	mi := &file_certificate_issue_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertificateResponse) ProtoMessage() {}

func (x *CertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_certificate_issue_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertificateResponse.ProtoReflect.Descriptor instead.
func (*CertificateResponse) Descriptor() ([]byte, []int) {
	return file_certificate_issue_service_proto_rawDescGZIP(), []int{1}
}

func (x *CertificateResponse) GetCertificate() string {
	if x != nil {
		return x.Certificate
	}
	return ""
}

func (x *CertificateResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *CertificateResponse) GetIssuingCa() string {
	if x != nil {
		return x.IssuingCa
	}
	return ""
}

func (x *CertificateResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *CertificateResponse) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

var File_certificate_issue_service_proto protoreflect.FileDescriptor

const file_certificate_issue_service_proto_rawDesc = "" +
	"\n" +
	"\x1fcertificate_issue_service.proto\x12\vsentinel_zt\"7\n" +
	"\x12CertificateRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\xb5\x01\n" +
	"\x13CertificateResponse\x12 \n" +
	"\vcertificate\x18\x01 \x01(\tR\vcertificate\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\tR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"issuing_ca\x18\x03 \x01(\tR\tissuingCa\x12#\n" +
	"\rserial_number\x18\x04 \x01(\tR\fserialNumber\x12\x17\n" +
	"\apod_uid\x18\x05 \x01(\tR\x06podUid2o\n" +
	"\x18CertificateIssuerService\x12S\n" +
	"\x0egetCertificate\x12\x1f.sentinel_zt.CertificateRequest\x1a .sentinel_zt.CertificateResponseB\fZ\n" +
	"grpc/protob\x06proto3"

var (
	file_certificate_issue_service_proto_rawDescOnce sync.Once
	file_certificate_issue_service_proto_rawDescData []byte
)

func file_certificate_issue_service_proto_rawDescGZIP() []byte {
	file_certificate_issue_service_proto_rawDescOnce.Do(func() {
		file_certificate_issue_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_certificate_issue_service_proto_rawDesc), len(file_certificate_issue_service_proto_rawDesc)))
	})
	return file_certificate_issue_service_proto_rawDescData
}

var file_certificate_issue_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_certificate_issue_service_proto_goTypes = []any{
	(*CertificateRequest)(nil),  // 0: sentinel_zt.CertificateRequest
	(*CertificateResponse)(nil), // 1: sentinel_zt.CertificateResponse
}
var file_certificate_issue_service_proto_depIdxs = []int32{
	0, // 0: sentinel_zt.CertificateIssuerService.getCertificate:input_type -> sentinel_zt.CertificateRequest
	1, // 1: sentinel_zt.CertificateIssuerService.getCertificate:output_type -> sentinel_zt.CertificateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_certificate_issue_service_proto_init() }
func file_certificate_issue_service_proto_init() {
	if File_certificate_issue_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_certificate_issue_service_proto_rawDesc), len(file_certificate_issue_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_certificate_issue_service_proto_goTypes,
		DependencyIndexes: file_certificate_issue_service_proto_depIdxs,
		MessageInfos:      file_certificate_issue_service_proto_msgTypes,
	}.Build()
	File_certificate_issue_service_proto = out.File
	file_certificate_issue_service_proto_goTypes = nil
	file_certificate_issue_service_proto_depIdxs = nil
}
