// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/certificate_issue_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CertificateIssuerService_GetCertificate_FullMethodName = "/sentinel_zt.CertificateIssuerService/getCertificate"
)

// CertificateIssuerServiceClient is the client API for CertificateIssuerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CertificateIssuerServiceClient interface {
	GetCertificate(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error)
}

type certificateIssuerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCertificateIssuerServiceClient(cc grpc.ClientConnInterface) CertificateIssuerServiceClient {
	return &certificateIssuerServiceClient{cc}
}

func (c *certificateIssuerServiceClient) GetCertificate(ctx context.Context, in *CertificateRequest, opts ...grpc.CallOption) (*CertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CertificateResponse)
	err := c.cc.Invoke(ctx, CertificateIssuerService_GetCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CertificateIssuerServiceServer is the server API for CertificateIssuerService service.
// All implementations must embed UnimplementedCertificateIssuerServiceServer
// for forward compatibility.
type CertificateIssuerServiceServer interface {
	GetCertificate(context.Context, *CertificateRequest) (*CertificateResponse, error)
	mustEmbedUnimplementedCertificateIssuerServiceServer()
}

// UnimplementedCertificateIssuerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCertificateIssuerServiceServer struct{}

func (UnimplementedCertificateIssuerServiceServer) GetCertificate(context.Context, *CertificateRequest) (*CertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCertificate not implemented")
}
func (UnimplementedCertificateIssuerServiceServer) mustEmbedUnimplementedCertificateIssuerServiceServer() {
}
func (UnimplementedCertificateIssuerServiceServer) testEmbeddedByValue() {}

// UnsafeCertificateIssuerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertificateIssuerServiceServer will
// result in compilation errors.
type UnsafeCertificateIssuerServiceServer interface {
	mustEmbedUnimplementedCertificateIssuerServiceServer()
}

func RegisterCertificateIssuerServiceServer(s grpc.ServiceRegistrar, srv CertificateIssuerServiceServer) {
	// If the following call panics, it indicates UnimplementedCertificateIssuerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CertificateIssuerService_ServiceDesc, srv)
}

func _CertificateIssuerService_GetCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CertificateIssuerServiceServer).GetCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CertificateIssuerService_GetCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CertificateIssuerServiceServer).GetCertificate(ctx, req.(*CertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CertificateIssuerService_ServiceDesc is the grpc.ServiceDesc for CertificateIssuerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertificateIssuerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentinel_zt.CertificateIssuerService",
	HandlerType: (*CertificateIssuerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getCertificate",
			Handler:    _CertificateIssuerService_GetCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/certificate_issue_service.proto",
}
