apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: database
  labels:
    app.kubernetes.io/name: postgresql
  type: Opaque
  data:
    postgres-password: cG9zdGdyZXM=
    replication-password: cG9zdGdyZXM=
