kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.cri.v1.cri".registry.configs."localhost:30500".tls]
      insecure_skip_verify = true
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
      - containerPort: 30001
        hostPort: 8200
        protocol: TCP
      - containerPort: 30443
        hostPort: 8443
        protocol: TCP
      - containerPort: 30500
        hostPort: 5000
        protocol: TCP
