{{- if .Values.webhook.enabled }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace "webhook-ca" }}
{{- $caBundle := "" }}
{{- if $secret }}
{{- $caBundle = index $secret.data "root_ca.crt" }}
{{- end }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sentinel-sidecar-injector
  labels:
    {{- include "sentinel.labels" . | nindent 4 }}
webhooks:
  - name: injector.sentinel-zt.io
    failurePolicy: Fail
    clientConfig:
      service:
        name: {{ include "sentinel.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /webhook/mutate
        port: {{ .Values.containers.port }}
      caBundle: {{ $caBundle }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
    namespaceSelector:
      matchLabels:
        sentinel-zt.io/injection: enabled
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - sentinel-control-plane
            - sentinel-data-plane
            - kube-system
            - argocd
            - default
{{- end }}
