apiVersion: v1
kind: Secret
metadata:
  name: echo-service-secret
  namespace: echo-service
type: Opaque
stringData:
  PORT: "3010"
  HOST: "0.0.0.0"
  LOOP_INTERVAL_MS: "30000"
  USERS_SERVICE_URL: "http://users-service.users-service.svc.cluster.local/api/health"
