apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: git@github.com:SamSyntax/Sentinel-Zero-Trust.git
    targetRevision: master
    path: dummy-services/users-service/k8s
  destination:
    server: http://kubernetes.default.svc
    namespace: users-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
