apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-configure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
spec:
  project: default
  source:
    repoURL: git@github.com:SamSyntax/Sentinel-Zero-Trust.git
    targetRevision: master
    path: infra/k8s/vault/configure
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
