FROM oven/bun:1-alpine AS base
WORKDIR /usr/src/app

FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lock drizzle.config.ts /temp/dev/
COPY src /temp/dev/src
RUN cd /temp/dev && bun install --frozen-lockfile

RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production

FROM base AS release
COPY --from=install /temp/dev/node_modules node_modules
COPY --from=install /temp/dev/src src
COPY package.json bun.lock drizzle.config.ts ./
COPY src ./src

USER bun
EXPOSE 3005/tcp
ENTRYPOINT [ "bun", "run", "src/index.ts" ]
