server:
  dev:
    enabled: false
    devRootToken: root

  standalone:
    enabled: true
    config: |
      ui = true
      listener "tcp" {
        address = "[::]:8200"
        tls_disable = 1
      }
      storage "raft" {
        path = "/vault/data"
      }

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: "standard"

injector:
  enabled: false
