apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: default
data:
  Caddyfile: |
    :80 {
      reverse_proxy http://argocd-server.argocd.svc.cluster.local:80
    }
    :8080 {
        reverse_proxy users-service.users-service.svc.cluster.local:80
    }
