apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: default
data:
  Caddyfile: |
    :80 {
        bind :80
        reverse_proxy argocd-server.argocd.svc.cluster.local:80
    }
    :8080 {
        bind :8080
        reverse_proxy users-service.users-service.svc.cluster.local:80
    }
