apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: default
data:
  Caddyfile: |
    :80 {
      @grpc header Content-Type application/grpc*
      handle @grpc {
        reverse_proxy h2c://argocd-server.argocd.svc.cluster.local:80
      }
      handle {
        reverse_proxy argocd-server.argocd.svc.cluster.local:80
      }
    }
    :8080 {
      reverse_proxy users-service.users-service.svc.cluster.local:80
    }
