apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sentinel-data.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "sentinel-data.labels" . | nindent 4 }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sentinel-data.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
      labels:
        {{- include "sentinel-data.selectorLabels" . | nindent 8 }}
        sentinel-zt: "injected"
    spec:
      serviceAccountName: {{ include "sentinel-data.serviceAccountName" . }}
      initContainers:
        - name: {{ .Values.initContainer.name }}
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
          imagePullPolicy: {{ .Values.initContainer.image.pullPolicy }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          args: ["--inboundPort", {{ .Values.initContainer.inboundPort | quote }}, "--outboundPort", {{ .Values.initContainer.outboundPort | quote }}]
      containers:
        - name: {{ .Values.containers.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort | default 15006 }}
          env:
            - name: CONTROL_PLANE_URL
              value: {{ printf "http://%s.%s.svc.cluster.local:%d/api/v1/identity/issue" .Values.controlPlane.serviceName .Values.controlPlane.namespace (int .Values.controlPlane.port) | quote }}
            - name: TARGET_GRPC
              value: {{ printf "%s.%s.svc.cluster.local:%d" .Values.controlPlane.serviceName .Values.controlPlane.namespace (int .Values.controlPlane.grpcPort) | quote }}
            - name: ENV
              value: "kind-local"
            - name: SPIFFE_TRUST_DOMAIN
              value: {{ .Values.spiffe.trustDomain | quote }}
            - name: PROXY_MODE
              value: "redirect"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CA_CERT_PATH
              value: "/etc/certs/root_ca.crt"
          volumeMounts:
            - name: vault-ca-volume
              mountPath: "/etc/certs"
              readOnly: true
          securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add: ["NET_ADMIN"]
      volumes:
        - name: vault-ca-volume
          secret:
            secretName: {{ .Values.caSecretName }}
