apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-data.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sentinel-data.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8443
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
