apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: users-service
  labels:
    app: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
      annotations:
        sentinel-zt.io/inject: "true"
        sentinel-zt.io/service-name: "users-service"
        sentinel-zt.io/target-port: "3005"
    spec:
      serviceAccountName: users-service
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - users-service
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: api
          image: localhost:30500/users-service
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          envFrom:
            - secretRef:
                name: users-service-secret
